.PHONY: clean All

All:
	@echo "----------Building project:[ simplefifo - Debug ]----------"
	@cd "simplefifo" && "$(MAKE)" -f  "simplefifo.mk"
clean:
	@echo "----------Cleaning project:[ simplefifo - Debug ]----------"
	@cd "simplefifo" && "$(MAKE)" -f  "simplefifo.mk" clean
